export const eventsData = [
  {
    id: 1,
    title: "SHARK TANK",
    category: "technical",
    tagline: "App Pitching Competition",
    description: "Got a creative app concept? Sell your idea to the sharks and prove why your innovation deserves to go big!",
    image: "/eventcards/shark-tank.jpg",
    date: "3rd December",
    time: "10:30 AM",
    organizer: "Ms. Saakshi Shetty – 9606469357",
    contact: "+91 9606469357",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-purple-500 to-pink-600",
    venue: "EDUSAT",
    location: "EDUSAT",
    studentCoordinator: "Lohith Gowda – 9019844009",
    detailedRules: [
      "2 to 4 members make a team",
      "The pitch should be completed in 3-5 minutes, and the QnA with Judges in 5 minutes",
      "Visual Aids/Props: PowerPoint/Pitch Deck (optional)",
      "The pitch should contain: Problem Statement, Solution, Target Market, Competitive Advantages, Financials",
      "Judgement will be given on: Innovation, Feasibility, Market Potential, Financial Understanding"
    ]
  },
  {
    id: 2,
    title: "STRATEGIC IT VISION",
    category: "technical",
    tagline: "IT Manager Challenge",
    description: "Join the summit of innovation and leadership—where IT minds redefine the future.",
    image: "/eventcards/it-vision.jpg",
    date: "3rd December",
    time: "10:30 AM",
    organizer: "Mr. Thejash – 8075773051",
    contact: "+91 8075773051",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-blue-500 to-cyan-600",
    venue: "CL-203",
    location: "2nd Floor",
    studentCoordinator: "Sinchana P S – 7483081046",
    detailedRules: [
      "It is an individual participation event",
      "Each round will be an elimination round.",
      "Late submission or absence during any round will lead to disqualification."
    ]
  },
  {
    id: 3,
    title: "EYES OFF! CODE ON",
    category: "technical",
    tagline: "Blind Coding Challenge",
    description: "Code in the dark and let your logic take the lead—beat the clock with raw skill and fearless focus.",
    image: "/eventcards/Eyesoff.jpg",
    date: "3rd Decemeber",
    time: "2:00 PM",
    organizer: "Ms. Spoorthi B – 9482906943",
    contact: "+91 9482906943",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-indigo-500 to-purple-600",
    venue: "SIM Lab",
    location: "Basement",
    studentCoordinator: "Bandhavya K S – 8904827379",
    detailedRules: [
      "Max two participants",
      "Languages: Only C, Python, or Java are permitted.",
      "No Mixing: Each problem solution must use only one language",
      "Format: Screens will be turned off.",
      "Consist of two rounds"
    ]
  },
  {
    id: 4,
    title: "WEBVERSE",
    category: "technical",
    tagline: "Web Designing Competition",
    description: "Design with precision, code with imagination. Create modern web experiences that redefine digital innovation!",
    image: "/eventcards/webverse.jpg",
    date: "3rd December",
    time: "10:30 AM",
    organizer: "Ms. Deepthi – 9880501735",
    contact: "+91 9880501735",
    amount: "Varies",
    teamSize: "2 members",
    gradient: "from-green-500 to-emerald-600",
    venue: "Computer Lab",
    location: "2nd Floor",
    studentCoordinator: "Santosh Y M – 9611535134",
    detailedRules: [
      "Team must consist of exactly 2 members.",
      "Offline event – Internet usage is not allowed.",
      "Design must follow the given theme(no pre-built templates).",
      "Submit on time, late entries won't be accepted"
    ]
  },
  {
    id: 5,
    title: "LINE QUEST",
    category: "technical",
    tagline: "Line Follower Robot",
    description: "Race your robot to perfection! Build, code, and master a line-following bot that blends speed, precision, and smart control.",
    image: "/eventcards/linefollower.png",
    date: "3rd December",
    time: "10:00 AM",
    organizer: "Ms. Ankitha V Shetty",
    contact: "+91 8310866320",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-orange-500 to-red-600",
    venue: "FM Lab",
    location: "1st Floor",
    studentCoordinator: "Ms. S B Poorvi (9353181551) & Apeksha (+91 77954 63069)",
    detailedRules: [
      "Each team must consist of 3–5 members.",
      "The bot must operate fully autonomously after crossing the start line.",
      "Pre-built or shared bots are strictly not allowed.",
      "The track may include curves and intersections of 3 cm width.",
      "Final score = Time taken + Penalty (Judges' decision is final)."
    ]
  },
  {
    id: 6,
    title: "ERROR EXTERMINATOR",
    category: "technical",
    tagline: "Debug the Code",
    description: "Hunt bugs, squash errors, beat the timer—show off lightning-fast debugging skills!",
    image: "/eventcards/errrorelimination.jpg",
    date: "3rd December",
    time: "12:00 PM",
    organizer: "Ms. Latha K V – 9611095629",
    contact: "+91 9611095629",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-red-500 to-pink-600",
    venue: "ISE Lab",
    location: "1st Floor",
    studentCoordinator: "Ankitha S A – 8591845188",
    detailedRules: [
      "Individual Participation",
      "Languages Allowed: C and Python",
      "Use of Internet and Electronic devices is prohibited",
      "Bonus points will be awarded for the early submission",
      "Round 1- Debugging Quiz, Round 2- Speed Debugging"
    ]
  },
  {
    id: 7,
    title: "DASHING DASHBOARDS",
    category: "technical",
    tagline: "Data Visualization Challenge",
    description: "Transform raw data into stunning visuals and spotlight your analytical flair with dashboards that wow!",
    image: "/eventcards/dashing-dashboard.jpg",
    date: "3rd December",
    time: "10:30 AM",
    organizer: "Ms. Meenakshi – 8088994353",
    contact: "+91 8088994353",
    amount: "Varies",
    teamSize: "1-2 members",
    gradient: "from-teal-500 to-blue-600",
    venue: "VLSI Lab",
    location: "1st Floor",
    studentCoordinator: "Karthik A T – 9353493357",
    detailedRules: [
      "Individual or team of 2 (dataset provided, no external data).",
      "Use Power BI or Tableau only.",
      "2 hours will be provided for data preparation, visualization, and dashboard creation.",
      "At least 3 key visualizations; 2–4 min presentation.",
      "Judging : Insight (30%), Creativity (25%), Clarity (25%), Interactivity (20%)."
    ]
  },
  {
    id: 8,
    title: "UXPERTS",
    category: "technical",
    tagline: "Poster Designing",
    description: "Create designs that make people stop and look—turn imagination into head-turning visuals!",
    image: "/eventcards/ui-experts.jpg",
    date: "3rd December",
    time: "11:30 AM",
    organizer: "Ms. Kyathi – 8296849083",
    contact: "+91 8296849083",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-pink-500 to-rose-600",
    venue: "CAED Lab",
    location: "Basement",
    studentCoordinator: "Janhavi Rathod – 7208773651",
    detailedRules: [
      "Individual participation",
      "Required software will be provided (Figma, Canva, Photoshop)",
      "Use of any personal gadget is not allowed",
      "Topic will be assigned on the spot",
      "Participants must manage their time to prevent clashes with other events"
    ]
  },
  {
    id: 9,
    title: "CODEWARS",
    category: "technical",
    tagline: "Competitive Coding",
    description: "A thrilling, time-bound coding showdown where speed meets skill and only the sharpest minds conquer the clock!",
    image: "/eventcards/codewars.jpg",
    date: "3rd December",
    time: "2:00 PM",
    organizer: "Mr. Savan Shetty – 6360841765",
    contact: "+91 6360841765",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-blue-600 to-indigo-700",
    venue: "ISE Lab",
    location: "1st Floor",
    studentCoordinator: "Nihal S Kolambkar – 7204196221",
    detailedRules: [
      "Individual Participation.",
      "Languages Allowed: C, C++, Java, Python.",
      "Use of Internet and Electronic devices is prohibited.",
      "Judged based on correctness of solution, code efficiency, execution speed and readability in approach.",
      "Round 1-Basic Problem Solving, Round 2- Advanced Problem solving."
    ]
  },
  {
    id: 10,
    title: "YAKSHA KALARAM",
    category: "special",
    tagline: "Yakshagana Performance",
    description: "A burst of myth, music, and dramatic expression takes over the stage—watch tradition explode in colours that refuse to sit still.",
    image: "/eventcards/yakshagana.jpg",
    date: "3rd December",
    time: "Revealing Soon",
    organizer: "Prof. Ananya J",
    contact: "+91 9845790058",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-yellow-600 to-orange-700",
    studentCoordinator: "S H Adithya (8073256702)",
    detailedRules: [
      "Individual Participation.",
      "Each participant will be given time period of 8+2 mins for Natya and Arthagarike.",
      "Himmela should be recorded.",
      "Judgement is based on the Costume, Natya and Arthagarike."
    ]
  },
  {
    id: 11,
    title: "SHRINGAR VISMAY",
    category: "special",
    tagline: "Fashion Walk",
    description: "The runway becomes a canvas where teams paint stories with fabric and attitude—every step a statement, every pose a spark.",
    image: "/eventcards/shrinagar.jpg",
    date: "3rd December",
    time: "Revealing Soon",
    organizer: "Prof. Anupama",
    contact: "Revealing Soon",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-pink-500 to-purple-600",
    studentCoordinator: "Sowparnika Shetty (9113810849)",
    detailedRules: [
      "4 to 6 members in a team",
      "Time : 4+1 mins",
      "Any theme is welcomed, so bring your creativity to the runway"
    ]
  },
  {
    id: 12,
    title: "RUN-BHUMI",
    category: "special",
    tagline: "Gully Cricket",
    description: "Three overs of pure chaos where reflexes rule and legends are born—gully spirit collides with raw competitive fire.",
    image: "/eventcards/run-bhumi.jpg",
    date: "3rd December",
    time: "Revealing Soon",
    organizer: "Prof. Suryakanth",
    contact: "+91 9980811082",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-green-600 to-emerald-700",
    studentCoordinator: "Chirag Shetty (8792876922)",
    detailedRules: [
      "6+1 players from a team and all of them should be from the same college",
      "3 over",
      "Different bowler",
      "Six will be considered as out",
      "Pitch-catch is considered not out",
      "ID card is compulsory",
      "Overarm bowling only"
    ]
  },
  {
    id: 13,
    title: "LUDO SAMRAT",
    category: "special",
    tagline: "Ludo Championship",
    description: "One board, many fates—every roll opens a new battlefield where strategy and luck wage a silent war.",
    image: "/eventcards/ludo-samrat.png",
    date: "3rd December",
    time: "Revealing Soon",
    organizer: "Prof. Diana D'Souza",
    contact: "+91 7795604890",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-red-500 to-orange-600",
    studentCoordinator: "Charan Reddy (9731596319)",
    detailedRules: [
      "No team-up",
      "Players should pre install Ludo King app in their mobile",
      "Any foul play will result in immediate disqualification"
    ]
  },
  {
    id: 14,
    title: "DRISHYA MAHIMA",
    category: "special",
    tagline: "Reel Making",
    description: "A challenge where creativity races the clock—shoot, edit, and deliver a reel that hooks viewers instantly.",
    image: "/eventcards/dhrishya.jpg",
    date: "3rd December",
    time: "Revealing Soon",
    organizer: "Prof. Pooja",
    contact: "Revealing Soon",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-purple-600 to-pink-600",
    studentCoordinator: "Jefin (7510593275)",
    detailedRules: [
      "Two in a team",
      "The reel must not exceed 60 seconds in length",
      "The reel must be an original creation by the participants",
      "Participants must submit their video within the allotted time"
    ]
  },
  {
    id: 16,
    title: "KOHJ KSHETRA",
    category: "cultural",
    tagline: "Treasure Hunt",
    description: "Clues twist, puzzles tease, and every step tests your nerve—only the sharpest minds reach the treasure’s final whisper.",
    image: "/eventcards/khoj.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Vignesh",
    contact: "+91 7204273146",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-amber-600 to-yellow-700",
    studentCoordinator: "Ananya rao (8147158229)",
    detailedRules: [
      "4 in a team",
      "Clues can be puzzles, riddles or links",
      "Do not tamper with other teams clues or disrupt their progress",
      "Cheating, tampering with other teams, or breaking any rules will result in disqualification"
    ]
  },
  {
    id: 17,
    title: "AGNI CHAKRAVYUHA",
    category: "cultural",
    tagline: "Free Fire Tournament",
    description: "A battleground where squads rise, fall, and fight for survival—precision and strategy decide the last player standing.",
    image: "/eventcards/free-fire.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Mohammed Hashim",
    contact: "+91 9061293705",
    amount: "Varies",
    teamSize: "4 members",
    gradient: "from-orange-600 to-red-700",
    studentCoordinator: "Ganesh (7483896493)",
    detailedRules: [
      "4 players per team (squad), one team per player",
      "Mobile only; no triggers, iPads, or emulators",
      "Players may bring thumb grips, earphones, etc",
      "Report 10 mins before match time.",
      "Map: Bermuda, Level : 30 above , elimination decided on spot.",
      "Use your own internet; lag won't count",
      "Cheating or misbehavior leads to disqualification."
    ]
  },
  {
    id: 18,
    title: "SHAKTHI SANGRAM",
    category: "cultural",
    tagline: "Tug of War",
    description: "Ropes strain, muscles fire, and teams pull with unshaken grit—strength finds purpose when the ground begins to slide.",
    image: "/eventcards/shakthi-sangram.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Suryakanth",
    contact: "+91 9980811082",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-blue-600 to-indigo-700",
    studentCoordinator: "Kishan kumar (7558892264)",
    detailedRules: [
      "Each team must consist of 7 players +1 subtitute player (all must be from the same college).",
      "Any number of team from one collage can participate.",
      "The combined team weight must not exceed 570kg (7 players). The 8th player (substitute player) must weigh at least 1 kg less than the lightest player among the 7 main team members.",
      "Shoulder pulling is strictly not allowed.",
      "Official team weighing (scaling) will be conducted on 28-11-2025 and must be completed before 10:00 AM.",
      "The decisions made by the Organizers and officials shall be final and binding.",
      "Any disputes or appeals will not be entertained beyond the officials' decision.",
      "The competition is open to both Postgraduate (PG) and Undergraduate (UG) students.",
      "College ID card is compulsory for all participants."
    ]
  },
  {
    id: 19,
    title: "TAAL YUDHA",
    category: "cultural",
    tagline: "Face-Off Dance",
    description: "The DJ drops the beat and dancers answer in lightning motion—a duel where rhythm becomes a weapon.",
    image: "/eventcards/faceoff.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Kyathi",
    contact: "+91 8296849083",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-purple-600 to-pink-700",
    studentCoordinator: "Siri V S (6362184296)",
    detailedRules: [
      "The dancers will be challenged to dance to the beats of a live DJ",
      "The music genre will change for each pair of dancers and can range from any genre of music such as rap, pop, breakbeats, funk etc",
      "Judges will choose 1 dancer from each battle to advance to the next round until the battle progresses to 2 final dancers"
    ]
  },
  {
    id: 20,
    title: "BHAVA SPHRUTHI",
    category: "cultural",
    tagline: "Solo Dance",
    description: "Grace, emotion, and discipline merge into a single moving story—classical dance taking center stage.",
    image: "/public/eventcards/bhava.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Spoorthi B Shetty",
    contact: "+91 9482906943",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-rose-500 to-pink-600",
    studentCoordinator: "Akshitha (7975059513)",
    detailedRules: [
      "Time limit: 3+1 mins",
      "Music should be submitted one day prior to the event",
      "Only classical and semi-classical dances are allowed",
      "Any number of participants from each college are allowed",
      "Use of fire, color and smoke are restricted"
    ]
  },
  {
    id: 21,
    title: "NRITHYA PARVA",
    category: "cultural",
    tagline: "Group Dance",
    description: "A symphony of feet, expressions, and flawless chemistry—every beat sends a wave of energy across the stage.",
    image: "/eventcards/groupdance.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Shwetha Rai",
    contact: "+91 7349013217",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-indigo-500 to-purple-600",
    studentCoordinator: "Sushmitha S k (9353249945)",
    detailedRules: [
      "6 to 10 in a team",
      "Time limit: 4+1 mins",
      "Any form of dance is allowed",
      "Multiple teams from each college are allowed to participate",
      "Use of fire, color and smoke are restricted",
      "Music should be submitted one day prior to the event"
    ]
  },
  {
    id: 22,
    title: "ANIME VICHAR",
    category: "cultural",
    tagline: "Anime Quiz",
    description: "Only true otaku minds survive this rapid-fire arena—one wrong answer and the arc collapses.",
    image: "/eventcards/anime.jpg",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Thejash",
    contact: "+91 8075773051",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-blue-500 to-cyan-600",
    studentCoordinator: "Chandan Ponnappa (6360162184)",
    detailedRules: [
      "Individual participation",
      "No electronic devices are allowed during the competition. Anyone found using them will be disqualified.",
      "A total of 4 rounds will be conducted"
    ]
  },
  {
    id: 23,
    title: "SANGEETH SPARSH",
    category: "cultural",
    tagline: "Solo Singing",
    description: "A single voice rises, the stage stills, and melody washes over the crowd—every note becomes a heartbeat.",
    image: "/eventcards/solo-singing.png",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Ashwini",
    contact: "+91 9743079974",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-teal-500 to-green-600",
    studentCoordinator: "Ananya R (9148136288)",
    detailedRules: [
      "Time limit: 3+1mins",
      "Singers can perform with or without karaoke",
      "Multiple participants from a college are welcome to join",
      "Each participant is allowed to use at most one instrument during their performance",
      "Singing can be in any language of choice",
      "Karaoke tracks should be submitted at least 2 days prior to the event"
    ]
  },
  {
    id: 24,
    title: "RANG MUKHAM",
    category: "cultural",
    tagline: "Face Painting",
    description: "Brushes dance across skin to create characters, moods, and illusions—art breathing through faces in real time.",
    image: "/eventcards/face.png",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Prafulla Shetty",
    contact: "+91 7204549248",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-pink-500 to-rose-600",
    studentCoordinator: "Harshitha Banjan (7559457095)",
    detailedRules: [
      "Two in a team",
      "Time limit : 2 hrs",
      "All necessary materials for face painting should be brought by the participants",
      "Topic will be given on the spot",
      "Only water color paints are allowed"
    ]
  },
  {
    id: 25,
    title: "CHAVI-CHITHRA",
    category: "cultural",
    tagline: "Photography",
    description: "The lens hunts moments that exist only once—pure photography with no edits and zero excuses.",
    image: "/eventcards/chavi-chithra.png",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Deepthi",
    contact: "+91 9880501735",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-gray-600 to-slate-700",
    studentCoordinator: "Joyston (8296839379)",
    detailedRules: [
      "Individual Participation",
      "All the pictures must be captured within the campus bounds",
      "One of the best picture of your capture must be submitted",
      "Images/photos must be captured only using the digital camera",
      "Editing and manipulation of image is not allowed"
    ]
  },
  {
    id: 26,
    title: "RANG DHARA",
    category: "cultural",
    tagline: "Brand Rangoli",
    description: "Colours weave brand stories in patterns that command attention—creativity blooming in every grain of rangoli.",
    image: "/eventcards/rangoli.png",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Roshal Lynshal Nazareth",
    contact: "+91 7899506648",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-orange-500 to-red-600",
    studentCoordinator: "Smruthi sudhakaran (8139885955)",
    detailedRules: [
      "Two make a team",
      "Time limit: 1 hrs",
      "Multiple Teams from the college are welcome to participate in the event"
    ]
  },
  {
    id: 27,
    title: "VEERA SAMARA",
    category: "cultural",
    tagline: "BGMI Tournament",
    description: "Four players, one mission—survive the map’s madness where quick minds and steady aim earn glory.",
    image: "/eventcards/bgmi.png",
    date: "4th December",
    time: "Revealing Soon",
    organizer: "Prof. Savan Shetty",
    contact: "+91 6360841765",
    amount: "Varies",
    teamSize: "team",
    gradient: "from-red-500 to-orange-600",
    studentCoordinator: "Jayasagar (7483013936)",
    detailedRules: [
      "Each team must have 4 players.",
      "Using hacks or cheats leads to disqualification.",
      "Only mobile phones allowed, no emulators.",
      "Player account must be level 30 or above",
      "Only registered players can play throughout the event",
      "Other instructions will be given on spot"
    ]
  },
  {
    id: 28,
    title: "PROTOVIEW",
    category: "technical",
    tagline: "Project Exhibition Showcase",
    description: "Present your idea to the world with confidence—your project could inspire the next big change!",
    image: "/eventcards/protoview.png",
    date: "3rd December",
    time: "11:00 AM",
    organizer: "Prof. Sheryl Iona Aiman",
    contact: "8197201536",
    amount: "Varies",
    teamSize: "2-4 members",
    gradient: "from-violet-600 to-purple-700",
    studentCoordinator: "Ms. Krithika (9902528313)",
    detailedRules: [
      "Teams must have between 2 and 4 members.",
      "Submit a project report (PDF) or presentation two days before the event.",
      "Presentations must be between 8 and 10 minutes.",
      "Demonstrate a safe working model or prototype during evaluation."
    ],
    venue: "CL-002",
    location: "Main Expo Hall"
  },
  {
    id: 29,
    title: "BOTFURY",
    category: "technical",
    tagline: "Robo Soccer Challenge",
    description: "Unleash the power of innovation on the field—the smartest bot takes the crown!",
    image: "/eventcards/botfury.png",
    date: "3rd December",
    time: "11:30 AM",
    organizer: "Prof. Deepa Kini",
    contact: "9886518868",
    amount: "Varies",
    teamSize: "2-3 members",
    gradient: "from-slate-600 to-blue-700",
    studentCoordinator: "Ms. Smitha S (8618657066)",
    detailedRules: [
      "Teams must consist of 2-3 members.",
      "The same bot must be used throughout all matches.",
      "Bots can be wired or wireless but must stay within 300 x 300 x 300 mm and 5 kg.",
      "Operating voltage must never exceed 12V; no external AC supply will be provided.",
      "Only leak-proof batteries are permitted."
    ],
    venue: "Mechanical Lab",
    location: "Robotics Arena"
  },
  {
    id: 30,
    title: "WORD2WORLD",
    category: "technical",
    tagline: "AI Interaction Challenge",
    description: "Put your AI-assisted problem solving to the test in a rapid, device-first challenge.",
    image: "/eventcards/word2world.png",
    date: "3rd December",
    time: "11:30 AM",
    organizer: "Prof. Prafulla Shetty",
    contact: "7204549248",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-cyan-500 to-blue-600",
    studentCoordinator: "Ms. Vaishnavi V (7676376109)",
    detailedRules: [
      "Individual participation only.",
      "Participants must bring their own device (mobile, tablet, or laptop).",
      "Internet connectivity must be arranged by the participant.",
      "AI tools to be used will be disclosed during the event."
    ],
    venue: "DSP Lab",
    location: "Innovation Hub"
  },
  {
    id: 31,
    title: "CIRCUIT CRAZE",
    category: "technical",
    tagline: "Mega Circuit Build",
    description: "Build smart and powerful circuits that bring ideas to life—show how strong your hardware skills really are!",
    image: "/eventcards/iot-league.png",
    date: "3rd December",
    time: "2:00 PM",
    organizer: "Prof. Ashwini P",
    contact: "9743079974",
    amount: "Varies",
    teamSize: "2 members",
    gradient: "from-emerald-500 to-teal-600",
    studentCoordinator: "Mr. Buddhapriya (6363807139)",
    detailedRules: [
      "Teams must consist of exactly 2 members.",
      "AI assistance is allowed during the build.",
      "Only the IoT components provided at the event may be used.",
      "External components or modules are strictly prohibited.",
      "Create and demonstrate a functional circuit within the allotted time."
    ],
    venue: "CAED Lab",
    location: "Basement"
  },
  {
    id: 32,
    title: "GERBER BATTLE",
    category: "technical",
    tagline: "PCB Design Showdown",
    description: "Where circuits meet creativity—design sleek, efficient PCBs that spark innovation.",
    image: "/eventcards/gerber-battle.png",
    date: "3rd December",
    time: "10:30 AM",
    organizer: "Prof. Diana D'Souza",
    contact: "7795604890",
    amount: "Varies",
    teamSize: "1-2 members",
    gradient: "from-amber-500 to-orange-600",
    studentCoordinator: "Ms. Gagana (8217579328)",
    detailedRules: [
      "Participate individually or as a team of two.",
      "Follow the provided circuit specification precisely.",
      "Use accurate footprints and maintain clear routing with proper spacing.",
      "Submit a design free from DRC errors.",
      "Bring a laptop with KiCad, OrCAD, or equivalent PCB software pre-installed."
    ],
    venue: "HDL Lab",
    location: "Basement"
  },
  {
    id: 33,
    title: "LUMINARY DESIGNS",
    category: "technical",
    tagline: "CAD Master Challenge",
    description: "Showcase your CAD creativity and compete for top rewards!",
    image: "/eventcards/luminary-designs.png",
    date: "3rd December",
    time: "1:30 PM",
    organizer: "Prof. Harsha G O",
    contact: "9731020393",
    amount: "Varies",
    teamSize: "individual",
    gradient: "from-blue-700 to-indigo-700",
    studentCoordinator: "Mr. T Karthik (9886502869), Ms. Varshini (9480287753)",
    detailedRules: [
      "Individual participation only.",
      "Total duration is 3 hours.",
      "A 2D drawing of a mechanical part will be provided for modeling.",
      "Event computers are available; participants may alternatively bring their own laptops.",
      "Required materials: pen, printout sheets, projector access, PC, writing pad."
    ],
    venue: "PG Building",
    location: "3rd floor"
  },
  {
    id: 34,
    title: "AQUA IGNITION",
    category: "technical",
    tagline: "Water Rocketry Contest",
    description: "Build, launch, and race your water rocket to victory!",
    image: "/eventcards/aqua-ignition.png",
    date: "3rd December",
    time: "12:00 PM",
    organizer: "Prof. Mohammed Hashim",
    contact: "9061293705",
    amount: "Varies",
    teamSize: "2 members",
    gradient: "from-sky-500 to-blue-600",
    studentCoordinator: "Mr. Sharan Basava (9591718284), Mr. Manoj (8088612422)",
    detailedRules: [
      "Teams must consist of 2 members.",
      "Electrical components or engines are not permitted.",
      "Teams receive a maximum of two launch attempts.",
      "Participants must bring 2-liter bottles for rocket construction.",
      "Carry pen, A4 sheets, and a writing pad for calculations and notes."
    ],
    venue: "Aerodynamic lab",
    location: "Launch Grounds"
  },
  {
    id: 35,
    title: "FLIGHT EMBERS",
    category: "technical",
    tagline: "Aircraft Investigation Challenge",
    description: "Analyze, evaluate, and present your investigation under pressure!",
    image: "/eventcards/flight-embers.png",
    date: "3rd December",
    time: "11:00 AM",
    organizer: "Prof. Augustine",
    contact: "9945471975",
    amount: "Approx. Prize: ₹4500",
    teamSize: "2 members",
    gradient: "from-orange-500 to-red-600",
    studentCoordinator: "Mr. Manohar (9980661580), Ms. Vinaya (7975758657)",
    detailedRules: [
      "Participation is in teams of two.",
      "Round 1: Quiz covering basic aircraft physics.",
      "Round 2: Identify the aircraft name and manufacturer.",
      "Round 3: Solve an aviation scenario and present an investigative report.",
      "Bring pen, A4 sheets, and a writing pad; miscellaneous expenses ₹800."
    ],
    venue: "CL-102",
    location: "Aero Briefing Room"
  }
];